### ISSUE TITLE
安装完成启动失败

### ISSUE THREAD

**Issue by cw58665466** [tmtbe/SwooleDistributed#62]
先是在 Mac 上用 composer 安装SD，安装完成后出现以下错误
```
☁  bin  php start_swoole_server.php list
Warning: Illegal string offset 'config_version' in /Users/xxx/xxx/sd/vendor/hassankhan/config/src/Parser/Php.php(37) : eval()'d code on line 8

Fatal error: Uncaught Noodlehaus\Exception\UnsupportedFormatException: PHP string does not return an array in /Users/xxx/xxx/sd/vendor/hassankhan/config/src/Parser/Php.php:54
Stack trace:
#0 /Users/xxx/xxx/sd/vendor/hassankhan/config/src/Config.php(97): Noodlehaus\Parser\Php->parse('3/**\n * Created...')
#1 /Users/xxx/xxx/sd/vendor/hassankhan/config/src/Config.php(62): Noodlehaus\Config->loadFromFile('/Users/xxx...', Object(Noodlehaus\Parser\Php))
#2 /Users/xxx/xxx/sd/vendor/tmtbe/swooledistributed/src/Server/Console/ChannelCmd.php(31): Noodlehaus\Config->__construct('/Users/xxx...')
#3 /Users/xxx/xxx/sd/vendor/tmtbe/swooledistributed/src/Server/Start.php(124): Server\Console\ChannelCmd->__construct('ChannelCmd')
#4 /Users/xxx/xxx/sd/vendor/tmtbe/swooledistributed/src/Server/Start.php(102): Server\Start::addDirCommand('/Users/chenjunj...', 'Server', Object(Symfony\Component\Console\Application) in /Users/xxx/xxx/sd/vendor/hassankhan/config/src/Parser/Php.php on line 54

```
起初是认为 Mac 或者环境的问题，后在一台纯净的centos上用
`curl -sS sd.youwoxing.net/install_v3 | bash`
仍然出现这个问题。
请问如何解决。

**Comment by jormin** [comment]
我测试安装 3.x 版本的时候也是这个问题，应该是 **[hassankhan/config](https://github.com/hassankhan/config)** 扩展的问题，这个库的作者最近发布了 **[2.0.0](https://github.com/hassankhan/config/releases/tag/2.0.0)** 版本，这个版本会造成上面说的配置异常问题，经测试更改为 **[1.1.0](https://github.com/hassankhan/config/releases/tag/1.1.0)** 后启动就正常了。

composer 配置如下：

```
{
  "require": {
    "tmtbe/swooledistributed":">3.2.6",
    "hassankhan/config":"1.1.0"
  },
 "autoload": {
    "psr-4": {
      "app\\": "src/app",
      "test\\": "src/test"
    }
  }
}
```

**Comment by zanedeng** [comment]
可以在config文件的顶部加上
`if (!is_array($config)) {
    $config = array();
}`

**Comment by zhyanbo** [comment]
vendor/hassankhan/config/src/Parser/Php.php文件中的parse函数的形参$config与配置文件中的$config冲突导致的，可以将parse函数中的$config替换为$config_str或其它不是$config的变量

**Comment by jormin** [comment]
> vendor/hassankhan/config/src/Parser/Php.php文件中的parse函数的形参$config与配置文件中的$config冲突导致的，可以将parse函数中的$config替换为$config_str或其它不是$config的变量

看作者怎么处理了，最好是不要修改依赖库源码，不过听闻作者现在不打算继续维护了？坊间传闻韩天峰大佬要接手SD 😅
